/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HAI;

import javax.swing.JFrame;

/**
 *
 * @author ACER-PC
 */
public class adminadduser extends javax.swing.JFrame {

    /**
     * Creates new form profile
     */
    
    public adminadduser() {
    setExtendedState(JFrame.MAXIMIZED_BOTH);  
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("TeXGyreAdventor", 0, 48)); // NOI18N
        jLabel1.setText("Daftar Pelamar Baru");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 30, 520, 60);

        jButton1.setText("Daftarkan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(630, 500, 90, 26);

        jLabel2.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel2.setText("Nama lengkap");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 142, 110, 15);

        jLabel3.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel3.setText("Tempat lahir");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 200, 180, 20);

        jLabel4.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel4.setText("Ketersediaan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 150, 130, 20);

        jLabel5.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 260, 70, 15);

        jLabel6.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel6.setText("Kota");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 290, 140, 20);

        jLabel7.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel7.setText("ID Keahlian Pel");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 300, 160, 20);

        jLabel8.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel8.setText("Lampiran");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 410, 80, 20);

        jButton7.setText("Tambahkan");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(610, 460, 110, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(211, 139, 143, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 200, 144, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 260, 144, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(210, 290, 144, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(210, 320, 144, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(210, 350, 144, 20);

        jLabel9.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel9.setText("ID Psikotes");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(410, 120, 100, 20);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(580, 150, 143, 20);

        jLabel11.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel11.setText("ID");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 116, 110, 15);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(211, 113, 143, 20);

        jLabel13.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel13.setText("Jenis Kelamin");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 170, 110, 15);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(210, 170, 143, 20);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(210, 230, 144, 20);

        jLabel14.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel14.setText("Tanggal lahir");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 230, 180, 20);

        jLabel15.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel15.setText("Email");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 350, 140, 20);

        jLabel16.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel16.setText("Nomor Telepon");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 320, 140, 20);

        jButton10.setText("Fotokopi ijazah");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(30, 430, 140, 30);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(580, 120, 143, 20);

        jLabel17.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel17.setText("Gaji Harapan");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(410, 180, 130, 20);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(580, 180, 143, 20);

        jLabel18.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel18.setText("Pendidikan");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(410, 210, 130, 20);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(580, 300, 143, 20);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(580, 210, 143, 20);

        jLabel12.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel12.setText("Status Berkeluarga");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(410, 240, 160, 20);

        jLabel19.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel19.setText("Keahlian Pelamar");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(410, 280, 160, 20);

        jLabel10.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel10.setText("Keahlian");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 330, 160, 20);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(580, 330, 143, 20);

        jButton12.setText("Browse Pas Foto");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(190, 430, 140, 30);

        jLabel20.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel20.setText("ID Dream Job");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(420, 400, 160, 20);
        getContentPane().add(jTextField16);
        jTextField16.setBounds(580, 400, 143, 20);

        jLabel21.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel21.setText("Dream Job Pelamar");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(410, 380, 160, 20);

        jLabel22.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel22.setText("Dream Job");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(420, 430, 160, 20);
        getContentPane().add(jTextField17);
        jTextField17.setBounds(580, 430, 143, 20);

        jButton13.setText("Tambahkan");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(610, 360, 110, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Worklampiran frm= new Worklampiran();
    frm.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminadduser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminadduser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminadduser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminadduser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new adminadduser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
