/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HAI;

import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.awt.HeadlessException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.sql.Connection;

import java.sql.Statement;
import javax.swing.JFrame;

import net.proteanit.sql.DbUtils;
import java.awt.print.PrinterException;
import java.text.MessageFormat;

import javax.swing.JTable.PrintMode;
import javax.swing.table.*;

import java.io.File;
import java.io.FileInputStream;

import java.io.InputStream;
import java.sql.DriverManager;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JFileChooser;
import java.io.File;  
/**
 *
 * @author ACER-PC
 */
public class MainMenu extends javax.swing.JFrame {

Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
Connect konek = new Connect();
File imageFile = null;
MysqlDataSource myDb = null;
int timerun = 0;        




    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        con= Connect.ConnectDB();
       

        Get_Data();
        Get_Data2();
        setLocationRelativeTo(null);
        new Thread(){
            public void run(){
                while (timerun == 0)
                {
                    Calendar cal = new GregorianCalendar();
                    
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    int AM_PM = cal.get(Calendar.AM_PM);
                    
                    String day_night = "";
                    if (AM_PM == 1){
                        day_night = "PM";
                    }
                    else
                    {
                        day_night = "AM";
                    }
                    String time = hour + ":" + min + ":" + sec + " " + day_night;
                    
                    Clock.setText(time);
                }
            }
    }.start();
                }
       

    
        private void Reset()
{
    txtid.setText("");
    txtnama.setText("");
    txtkelamin.setText("");
    txttempat.setText("");
    txttanggal.setText("");
    txtalamat.setText("");
    txtkota.setText("");
    txttelepon.setText("");
    txtemail.setText("");
    txtpsiko.setText("");
    combosedia1.setSelectedIndex(-1);
    txtgaji.setText("");
    txtpendidikan.setText("");
    txtstatus.setText("");
    txtkeahlian.setText("");
    txtdream.setText("");
    combokate1.setSelectedIndex(-1);
    Get_Data2();
}
        private void Reset1()
{
    btnid.setText("");
    btnnama.setText("");
    btnklmn.setText("");
    btntpt1.setText("");
    btntgl.setText("");
    btnalamat.setText("");
    btnkota.setText("");
    btnno.setText("");
    btnemail.setText("");
    btnidpsiko.setText("");
    combosedia.setSelectedIndex(-1);
    btngaji.setText("");
    btnpendi.setText("");
    btnkeluarga.setText("");
    btnkeahlian.setText("");
    btndream.setText("");
    combokate.setSelectedIndex(-1);
}
        private void Get_Data(){
        String sql="select * from tbdatapelamar";
          try{
         pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
         tabelview.setModel(DbUtils.resultSetToTableModel(rs));
         tabelview.setDefaultEditor(Object.class, null);
         tabelview.setAutoCreateRowSorter(true);
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          
}
        }
           private void Get_Data2(){
        String sql="select * from tbdatapelamar";
          try{
         pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
         tabelview2.setModel(DbUtils.resultSetToTableModel(rs));
         tabelview2.setDefaultEditor(Object.class, null);
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          
}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelview = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        Clock = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelview2 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtkelamin = new javax.swing.JTextField();
        txttempat = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttanggal = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtkota = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        txtpsiko = new javax.swing.JTextField();
        txtgaji = new javax.swing.JTextField();
        txtpendidikan = new javax.swing.JTextField();
        txtstatus = new javax.swing.JTextField();
        txtkeahlian = new javax.swing.JTextField();
        txtdream = new javax.swing.JTextField();
        combokate1 = new javax.swing.JComboBox<>();
        btnnew = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        combosedia1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btninsert = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        btnemail = new javax.swing.JTextField();
        btnnama = new javax.swing.JTextField();
        btnklmn = new javax.swing.JTextField();
        btntgl = new javax.swing.JTextField();
        btnalamat = new javax.swing.JTextField();
        btnkota = new javax.swing.JTextField();
        btnno = new javax.swing.JTextField();
        btnid = new javax.swing.JTextField();
        btnidpsiko = new javax.swing.JTextField();
        btngaji = new javax.swing.JTextField();
        btnpendi = new javax.swing.JTextField();
        btnkeluarga = new javax.swing.JTextField();
        btndream = new javax.swing.JTextField();
        labelimage = new javax.swing.JLabel();
        btnkeahlian = new javax.swing.JTextField();
        combokate = new javax.swing.JComboBox<>();
        btntpt1 = new javax.swing.JTextField();
        combosedia = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(208, 240, 238));
        jPanel4.setLayout(null);

        jButton1.setText("print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(541, 461, 388, 26);
        jPanel4.add(txtsearch);
        txtsearch.setBounds(195, 458, 162, 33);

        jButton4.setText("refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(408, 461, 76, 26);

        jButton3.setText("search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(195, 509, 162, 26);

        tabelview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelview);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1380, 220);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sda.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(1291, 610, 50, 20);

        Clock.setFont(new java.awt.Font("Digital-7", 0, 60)); // NOI18N
        Clock.setForeground(new java.awt.Color(0, 165, 255));
        Clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clock.setToolTipText("");
        jPanel4.add(Clock);
        Clock.setBounds(490, 220, 410, 90);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled-1.png"))); // NOI18N
        jPanel4.add(jLabel35);
        jLabel35.setBounds(0, 70, 1380, 610);

        jTabbedPane2.addTab("View Data                                      ", jPanel4);

        jPanel6.setLayout(null);

        tabelview2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelview2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelview2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelview2);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(0, 0, 1380, 250);

        jLabel20.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel20.setText("ID");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(130, 270, 110, 15);

        jLabel7.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel7.setText("Nama lengkap");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(130, 300, 110, 15);

        jLabel22.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel22.setText("Jenis Kelamin");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(130, 330, 110, 15);

        jLabel8.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel8.setText("Tempat lahir");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(130, 360, 100, 20);

        jLabel23.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel23.setText("Tanggal lahir");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(130, 390, 180, 20);

        jLabel10.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel10.setText("Alamat");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(130, 420, 70, 15);

        jLabel24.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel24.setText("Kota");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(130, 450, 140, 20);

        jLabel25.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel25.setText("Nomor Telepon");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(130, 480, 140, 20);

        jLabel26.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel26.setText("Email");
        jPanel6.add(jLabel26);
        jLabel26.setBounds(130, 510, 140, 20);

        jLabel27.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel27.setText("ID Psikotes");
        jPanel6.add(jLabel27);
        jLabel27.setBounds(510, 270, 100, 20);

        jLabel28.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel28.setText("Ketersediaan");
        jPanel6.add(jLabel28);
        jLabel28.setBounds(510, 300, 130, 20);

        jLabel29.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel29.setText("Gaji Harapan");
        jPanel6.add(jLabel29);
        jLabel29.setBounds(510, 330, 130, 20);

        jLabel30.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel30.setText("Pendidikan");
        jPanel6.add(jLabel30);
        jLabel30.setBounds(510, 360, 130, 20);

        jLabel31.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel31.setText("Status Berkeluarga");
        jPanel6.add(jLabel31);
        jLabel31.setBounds(510, 390, 160, 20);

        jLabel32.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel32.setText("Keahlian Pelamar");
        jPanel6.add(jLabel32);
        jLabel32.setBounds(510, 420, 160, 20);

        jLabel33.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel33.setText("Dream Job Pelamar");
        jPanel6.add(jLabel33);
        jLabel33.setBounds(510, 450, 160, 20);

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel6.add(txtid);
        txtid.setBounds(260, 270, 149, 30);
        jPanel6.add(txtkelamin);
        txtkelamin.setBounds(260, 330, 149, 30);

        txttempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttempatActionPerformed(evt);
            }
        });
        jPanel6.add(txttempat);
        txttempat.setBounds(260, 360, 149, 30);
        jPanel6.add(txtnama);
        txtnama.setBounds(260, 300, 149, 30);
        jPanel6.add(txtemail);
        txtemail.setBounds(260, 510, 149, 30);
        jPanel6.add(txttanggal);
        txttanggal.setBounds(260, 390, 149, 30);
        jPanel6.add(txtalamat);
        txtalamat.setBounds(260, 420, 149, 30);
        jPanel6.add(txtkota);
        txtkota.setBounds(260, 450, 149, 30);
        jPanel6.add(txttelepon);
        txttelepon.setBounds(260, 480, 149, 30);
        jPanel6.add(txtpsiko);
        txtpsiko.setBounds(670, 270, 149, 30);
        jPanel6.add(txtgaji);
        txtgaji.setBounds(670, 330, 149, 30);

        txtpendidikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpendidikanActionPerformed(evt);
            }
        });
        jPanel6.add(txtpendidikan);
        txtpendidikan.setBounds(670, 360, 149, 30);
        jPanel6.add(txtstatus);
        txtstatus.setBounds(670, 390, 149, 30);
        jPanel6.add(txtkeahlian);
        txtkeahlian.setBounds(670, 420, 149, 30);
        jPanel6.add(txtdream);
        txtdream.setBounds(670, 450, 149, 30);

        combokate1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendidikan", "Teknologi", "Item 3", "Item 4" }));
        combokate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combokate1ActionPerformed(evt);
            }
        });
        jPanel6.add(combokate1);
        combokate1.setBounds(670, 490, 150, 25);

        btnnew.setText("new");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });
        jPanel6.add(btnnew);
        btnnew.setBounds(420, 540, 81, 26);

        btnupdate.setText("update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel6.add(btnupdate);
        btnupdate.setBounds(520, 540, 81, 26);

        btndelete.setText("delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel6.add(btndelete);
        btndelete.setBounds(620, 540, 81, 26);

        combosedia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vacant", "not_vacant" }));
        combosedia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combosedia1ActionPerformed(evt);
            }
        });
        jPanel6.add(combosedia1);
        combosedia1.setBounds(670, 300, 150, 25);

        jButton2.setText("refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(10, 260, 76, 26);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sda.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7);
        jButton7.setBounds(1291, 610, 50, 20);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/L5fanw.jpg"))); // NOI18N
        jPanel6.add(jLabel38);
        jLabel38.setBounds(0, 70, 1440, 610);

        jTabbedPane2.addTab("Edit data                                                     ", jPanel6);

        jPanel5.setLayout(null);

        jLabel1.setText("Daftar Pelamar Baru");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(410, 40, 129, 16);

        jLabel11.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel11.setText("ID");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(20, 110, 110, 15);

        jLabel2.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel2.setText("Nama lengkap");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(20, 150, 110, 15);

        jLabel13.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel13.setText("Jenis Kelamin");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(20, 190, 110, 15);

        jLabel3.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel3.setText("Tempat lahir");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(20, 220, 100, 20);

        jLabel14.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel14.setText("Tanggal lahir");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(20, 260, 180, 20);

        jLabel5.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel5.setText("Alamat");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(20, 310, 70, 15);

        jLabel6.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel6.setText("Kota");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(20, 340, 140, 20);

        jLabel16.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel16.setText("Nomor Telepon");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(20, 380, 140, 20);

        jLabel15.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel15.setText("Email");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(20, 420, 140, 20);

        jLabel9.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel9.setText("ID Psikotes");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(400, 110, 100, 20);

        jLabel4.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel4.setText("Ketersediaan");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(400, 140, 130, 20);

        jLabel17.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel17.setText("Gaji Harapan");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(400, 180, 130, 20);

        jLabel18.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel18.setText("Pendidikan");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(400, 220, 130, 20);

        jLabel12.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel12.setText("Status Berkeluarga");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(400, 260, 160, 20);

        jLabel19.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel19.setText("Keahlian Pelamar");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(400, 300, 160, 20);

        btninsert.setText("Tambahkan");
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });
        jPanel5.add(btninsert);
        btninsert.setBounds(530, 430, 120, 26);

        jLabel21.setFont(new java.awt.Font("TeXGyreAdventor", 0, 14)); // NOI18N
        jLabel21.setText("Dream Job Pelamar");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(400, 340, 160, 20);

        btnemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemailActionPerformed(evt);
            }
        });
        jPanel5.add(btnemail);
        btnemail.setBounds(140, 420, 170, 30);

        btnnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnamaActionPerformed(evt);
            }
        });
        jPanel5.add(btnnama);
        btnnama.setBounds(140, 140, 170, 30);

        btnklmn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnklmnActionPerformed(evt);
            }
        });
        jPanel5.add(btnklmn);
        btnklmn.setBounds(140, 180, 170, 30);

        btntgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntglActionPerformed(evt);
            }
        });
        jPanel5.add(btntgl);
        btntgl.setBounds(140, 260, 170, 30);

        btnalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalamatActionPerformed(evt);
            }
        });
        jPanel5.add(btnalamat);
        btnalamat.setBounds(140, 300, 170, 30);

        btnkota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkotaActionPerformed(evt);
            }
        });
        jPanel5.add(btnkota);
        btnkota.setBounds(140, 340, 170, 30);

        btnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnoActionPerformed(evt);
            }
        });
        jPanel5.add(btnno);
        btnno.setBounds(140, 380, 170, 30);

        btnid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnidActionPerformed(evt);
            }
        });
        jPanel5.add(btnid);
        btnid.setBounds(140, 100, 170, 30);

        btnidpsiko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnidpsikoActionPerformed(evt);
            }
        });
        jPanel5.add(btnidpsiko);
        btnidpsiko.setBounds(570, 100, 170, 30);

        btngaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngajiActionPerformed(evt);
            }
        });
        jPanel5.add(btngaji);
        btngaji.setBounds(570, 180, 170, 30);

        btnpendi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpendiActionPerformed(evt);
            }
        });
        jPanel5.add(btnpendi);
        btnpendi.setBounds(570, 220, 170, 30);

        btnkeluarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluargaActionPerformed(evt);
            }
        });
        jPanel5.add(btnkeluarga);
        btnkeluarga.setBounds(570, 260, 170, 30);

        btndream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndreamActionPerformed(evt);
            }
        });
        jPanel5.add(btndream);
        btndream.setBounds(570, 340, 170, 30);

        labelimage.setBackground(new java.awt.Color(0, 0, 0));
        labelimage.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(labelimage);
        labelimage.setBounds(770, 100, 160, 150);

        btnkeahlian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeahlianActionPerformed(evt);
            }
        });
        jPanel5.add(btnkeahlian);
        btnkeahlian.setBounds(570, 300, 170, 30);

        combokate.setBackground(new java.awt.Color(255, 255, 255));
        combokate.setForeground(new java.awt.Color(102, 102, 102));
        combokate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kategori", "Administrasi Eksekutif", "Administrasi Pemerintahan", "Akuntansi", "Alat medis", "Alat olahraga", "Alat dan perlengkapan bisnis", "Animasi", "Arsitektur dan perancangan", "Asuransi", "Aviasi & penerbangan", "Bahan kimia", "Barang konsumsi", "Barang mewah & perhiasan", "Barang-barang elektronik", "Belajar Online", "Bioteknologi", "Daur ulang & Lingkungan", "Desain", "Desain Grafis", "Farmasi", "Fasilitas & Layanan Rekreasi", "Fotografi", "Gambar bergerak & film", "Game komputer", "Hiburan", "Hubungan Internasional", "Hubungan masyarakat", "Hubungan Pemerintah", "impor & ekspor", "Internet", "Jaringan komputer", "Jasa Keuangan", "Judi & kasino", "kaca, keramik & beton", "Kantor legislatif", "Keamanan & investigasi", "Keamanan publik ", "Kebijakan publik", "kedermawaan", "Manajemen Organisasi Nirlaba", "Manajemen pendidikan", "Manajemen jalur kereta api", "Manufaktur listrik dan Elektronik", "Maritim", "Maskapai penerbangan", "Material Bangunan", "Media cetak", "Media Penyiaran", "Militer", "Minyak dan energi", "Modal Usaha", "Museum & Institusi", "Musik", "Nanoteknologi", "Nirkabel", "Olahraga", "Organisasi politik", "Organisasi sosial", "Otomasi industri", "Otomotif", "Pakaian & Mode", "Penerbitan", "Penerjamahan", "Perabot Rumah Tangga", "Peradilan", "Praktik Hukum", "Real estate", "Research", "Restoran", "Riset pasar", "Ritel", "Sumber Daya Manusia", "Supermarket", "Teknik Mesin dan Industri", "Teknik Sipil" }));
        combokate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combokateActionPerformed(evt);
            }
        });
        jPanel5.add(combokate);
        combokate.setBounds(770, 300, 190, 25);

        btntpt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntpt1ActionPerformed(evt);
            }
        });
        jPanel5.add(btntpt1);
        btntpt1.setBounds(140, 220, 170, 30);

        combosedia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vacant", "not_vacant" }));
        combosedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combosediaActionPerformed(evt);
            }
        });
        jPanel5.add(combosedia);
        combosedia.setBounds(570, 140, 170, 25);
        jPanel5.add(jLabel34);
        jLabel34.setBounds(830, 270, 0, 0);

        jButton9.setText("Pilih File");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9);
        jButton9.setBounds(430, 430, 80, 26);

        jLabel37.setText("Choose File");
        jPanel5.add(jLabel37);
        jLabel37.setBounds(400, 390, 65, 16);
        jPanel5.add(jTextName);
        jTextName.setBounds(480, 390, 250, 20);

        jButton5.setText("new");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);
        jButton5.setBounds(660, 430, 70, 26);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sda.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);
        jButton8.setBounds(1291, 610, 50, 20);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/slide1.png"))); // NOI18N
        jPanel5.add(jLabel36);
        jLabel36.setBounds(0, 0, 1380, 680);

        jTabbedPane2.addTab("Insert data                                            ", jPanel5);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 0, 1381, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        tabelview.print(PrintMode.FIT_WIDTH, new MessageFormat("DATA PELAMAR"),null);
        } catch (PrinterException ex) {
        Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE,null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btntpt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntpt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntpt1ActionPerformed

    private void combokateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combokateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combokateActionPerformed

    private void btnkeahlianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeahlianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkeahlianActionPerformed

    private void btndreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndreamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndreamActionPerformed

    private void btnkeluargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkeluargaActionPerformed

    private void btnpendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpendiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpendiActionPerformed

    private void btngajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngajiActionPerformed

    private void btnidpsikoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnidpsikoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnidpsikoActionPerformed

    private void btnidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnidActionPerformed

    private void btnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnoActionPerformed

    private void btnkotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkotaActionPerformed

    private void btnalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnalamatActionPerformed

    private void btntglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntglActionPerformed

    private void btnklmnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnklmnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnklmnActionPerformed

    private void btnnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnamaActionPerformed

    private void btnemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnemailActionPerformed

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        
        try{
            con=Connect.ConnectDB();
            if (btnid.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter id","Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (btnnama.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter name","Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (btnklmn.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter gender","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (btntpt1.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter tempat lahir","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (btntgl.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter tanggal","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (btnalamat.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter alamat","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (btnkota.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter kota","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (btnno.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter nomor telepon","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (btnemail.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter email","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (btnidpsiko.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter id psiko","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (combosedia.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog( this, "Please select ketersediaan pegawai","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (btngaji.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter gaji","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (btnpendi.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter pendidikan pegawai","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (btnkeluarga.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter keluarga","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (btnkeahlian.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please select keahlian pegawai","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (btndream.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please select dream job pegawai","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (combokate.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog( this, "Please select kategori keahlian","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Statement stmt;
            stmt= con.createStatement();
            String sql1="Select idPelamar from tbdatapelamar where idPelamar= '" + btnid.getText() + "'";
            rs=stmt.executeQuery(sql1);
            if(rs.next()){
                JOptionPane.showMessageDialog( this, "ID already exists","Error", JOptionPane.ERROR_MESSAGE);
                btnid.setText("");
                btnid.requestDefaultFocus();
                return;
            }
            String sql= "insert into tbdatapelamar(idPelamar,nama,jenisKelamin,TempatLahir,TanggalLahir,alamat,Kota,noTelp,email,idPsikotest,"
            + "ketersediaan,gajiHarapan,pendidikan,statusberkeluarga,keahlian,Dream_Job,kategori)values('"+
            btnid.getText() + "','"+ btnnama.getText() + "','"+ btnklmn.getText() + "','"+ btntpt1.getText() + "','"
            + btntgl.getText() + "','" + btnalamat.getText() + "','"+ btnkota.getText() + "','" + btnno.getText() + "','"
            + btnemail.getText() + "','"+ btnidpsiko.getText() + "','"+ combosedia.getSelectedItem() + "','"+ btngaji.getText() + "','"
            + btnpendi.getText() + "','"+ btnkeluarga.getText() + "','"+ btnkeahlian.getText() + "','"+ btndream.getText() + "','"+ combokate.getSelectedItem() + "')";

            pst=con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this,"Successfully Registered","Patient",JOptionPane.INFORMATION_MESSAGE);
            btninsert.setEnabled(false);

        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }  
        String url = "jdbc:mysql://localhost:3306/hai";
        String user = "root";
        String password = "abc";
 
        String filePath = jTextName.getText();
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
 
            String sql = "INSERT INTO image (image) values (LOAD_FILE(?))";
            PreparedStatement statement = conn.prepareStatement(sql);
 
            statement.setString(1, filePath);
 
            int row = statement.executeUpdate();
            if (row > 0) {
                System.out.println("A contact was inserted with photo image.");
            }
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    
       
    }//GEN-LAST:event_btninsertActionPerformed

    private void txttempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttempatActionPerformed

    private void txtpendidikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpendidikanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpendidikanActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void tabelview2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelview2MouseClicked
        try{
            con=Connect.ConnectDB();
            int row= tabelview2.getSelectedRow();
            String table_click= tabelview2.getModel().getValueAt(row, 0).toString();
            String sql= "select * from tbdatapelamar where idpelamar = '" + table_click + "'";
            pst=con.prepareStatement(sql);
            rs=  pst.executeQuery();
            if(rs.next()){

                String add1=rs.getString("idpelamar");
                txtid.setText(add1);
                String add2=rs.getString("nama");
                txtnama.setText(add2);
                String add3 = rs.getString("jenisKelamin");
                txtkelamin.setText(add3);
                String add4= rs.getString("TempatLahir");
                txttempat.setText(add4);
                String add5 = rs.getString("TanggalLahir");
                txttanggal.setText(add5);
                String add6= rs.getString("alamat");
                txtalamat.setText(add6);
                 String add7=rs.getString("kota");
                txtkota.setText(add7);
                String add8=rs.getString("noTelp");
                txttelepon.setText(add8);
                String add9 = rs.getString("email");
                txtemail.setText(add9);
                String add10= rs.getString("idPsikotest");
                txtpsiko.setText(add10);
                String add11 = rs.getString("ketersediaan");
                combosedia1.setSelectedItem(add11);
                String add12 = rs.getString("gajiHarapan");
                txtgaji.setText(add12);
                String add13=rs.getString("pendidikan");
                txtpendidikan.setText(add13);
                String add14 = rs.getString("statusberkeluarga");
                txtstatus.setText(add14);
                String add15= rs.getString("Keahlian");
                txtkeahlian.setText(add15);
                String add16 = rs.getString("Dream_Job");
                txtdream.setText(add16);
                String add17 = rs.getString("kategori");
                combokate1.setSelectedItem(add17);
                btnupdate.setEnabled(true);

            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_tabelview2MouseClicked

    private void combokate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combokate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combokate1ActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        Reset();
    }//GEN-LAST:event_btnnewActionPerformed

    private void combosedia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combosedia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combosedia1ActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try{
            con=Connect.ConnectDB();
            String sql= "update tbdatapelamar set nama='" + txtnama.getText() + "',jenisKelamin='" + txtkelamin.getText() 
                    + "',TempatLahir='" + txttempat.getText() + "',TanggalLahir='" + txttanggal.getText() + "',alamat='" + txtalamat.getText() 
                    + "',Kota='" + txtkota.getText() + "',noTelp='" + txttelepon.getText() + "',email='" + txtemail.getText() + "',idPsikotest='" + txtpsiko.getText() 
                    + "',ketersediaan='" + combosedia1.getSelectedItem() + "',gajiHarapan='" + txtgaji.getText() 
                    + "',pendidikan='" + txtpendidikan.getText() + "',statusberkeluarga='" + txtstatus.getText() + "',keahlian='" + txtkeahlian.getText() + "',Dream_Job='" + txtdream.getText() 
                    + "',kategori='" + combokate1.getSelectedItem() + "' where idPelamar='" + txtid.getText() + "'";
            pst=con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this,"Successfully updated","Room Record",JOptionPane.INFORMATION_MESSAGE);
            btnupdate.setEnabled(false);
            Get_Data2();
            Reset();
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try
        {
            int P = JOptionPane.showConfirmDialog(null," Are you sure want to delete ?","Confirmation",JOptionPane.YES_NO_OPTION);
            if (P==0)
            {
                con=Connect.ConnectDB();
                String sql= "delete from tbdatapelamar where idPelamar = '" + txtid.getText() + "'";
                pst=con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this,"Successfully deleted","Record",JOptionPane.INFORMATION_MESSAGE);
                Reset();
            }
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void combosediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combosediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combosediaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String cari;
        cari = txtsearch.getText();
        
       try
        {
            Statement st = con.createStatement();
            String search = txtsearch.getText();
            ResultSet rs = st.executeQuery("SELECT * FROM tbdatapelamar WHERE idPelamar like '%"+search+"%' OR nama like '%"+search+"%' OR kota like '%"+search+"%'OR idPsikotest like '%"+search+"%'OR pendidikan like '%"+search+"%'OR kategori like '%"+search+"%'");
            DefaultTableModel dtm = (DefaultTableModel)tabelview.getModel();

            dtm.setRowCount(0);
            String [] data = new String[20];
            int i = 1;

            while(rs.next())
            {
                    data[0] = rs.getString("idPelamar");
                    data[1] = rs.getString("nama");
                    data[2] = rs.getString("jenisKelamin");
                    data[3] = rs.getString("TempatLahir");
                    data[4] = rs.getString("TanggalLahir");
                    data[5] = rs.getString("alamat");
                    data[6] = rs.getString("Kota");
                    data[7] = rs.getString("noTelp");
                    data[8] = rs.getString("email");
                    data[9] = rs.getString("idPsikotest");
                    data[10] = rs.getString("ketersediaan");
                    data[11] = rs.getString("gajiHarapan");
                    data[12] = rs.getString("pendidikan");
                    data[13] = rs.getString("statusberkeluarga");
                    data[14] = rs.getString("keahlian");
                    data[15] = rs.getString("Dream_Job");
                    data[16] = rs.getString("kategori");
                dtm.addRow(data);
                i++;
            }
            rs.close();
            txtsearch.setText("");
        }
        catch(Exception ex)  {
            JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
            System.err.println("error (search) : " +ex);
        }
           
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Get_Data();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Get_Data2();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        JFileChooser OpenFile = new JFileChooser();
        OpenFile.setMultiSelectionEnabled(false);
        OpenFile.showOpenDialog(null);
        File x_file = OpenFile.getSelectedFile();
        String NamaFile = x_file.getAbsolutePath();
        jTextName.setText(NamaFile);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Reset1();
        btninsert.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                    this.hide();
                    Login frmlogin = new Login();
                    frmlogin.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                    this.hide();
                    Login frmlogin = new Login();
                    frmlogin.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
                    this.hide();
                    Login frmlogin = new Login();
                    frmlogin.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clock;
    private javax.swing.JTextField btnalamat;
    private javax.swing.JButton btndelete;
    private javax.swing.JTextField btndream;
    private javax.swing.JTextField btnemail;
    private javax.swing.JTextField btngaji;
    private javax.swing.JTextField btnid;
    private javax.swing.JTextField btnidpsiko;
    private javax.swing.JButton btninsert;
    private javax.swing.JTextField btnkeahlian;
    private javax.swing.JTextField btnkeluarga;
    private javax.swing.JTextField btnklmn;
    private javax.swing.JTextField btnkota;
    private javax.swing.JTextField btnnama;
    private javax.swing.JButton btnnew;
    private javax.swing.JTextField btnno;
    private javax.swing.JTextField btnpendi;
    private javax.swing.JTextField btntgl;
    private javax.swing.JTextField btntpt1;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> combokate;
    private javax.swing.JComboBox<String> combokate1;
    private javax.swing.JComboBox<String> combosedia;
    private javax.swing.JComboBox<String> combosedia1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextName;
    private javax.swing.JLabel labelimage;
    private javax.swing.JTable tabelview;
    private javax.swing.JTable tabelview2;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtdream;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtgaji;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtkeahlian;
    private javax.swing.JTextField txtkelamin;
    private javax.swing.JTextField txtkota;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpendidikan;
    private javax.swing.JTextField txtpsiko;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JTextField txttanggal;
    private javax.swing.JTextField txttelepon;
    private javax.swing.JTextField txttempat;
    // End of variables declaration//GEN-END:variables
}
