/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HAI;

/**
 *
 * @author ACER-PC
 */
public class profile extends javax.swing.JFrame {

    /**
     * Creates new form profile
     */
    public profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("TeXGyreAdventor", 0, 48)); // NOI18N
        jLabel1.setText("Profile");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 30, 150, 60);

        jButton1.setText("new");
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 90, 53, 23);

        jButton2.setText("save");
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 90, 55, 23);

        jButton3.setText("delete");
        getContentPane().add(jButton3);
        jButton3.setBounds(350, 90, 63, 23);

        jButton4.setText("update");
        getContentPane().add(jButton4);
        jButton4.setBounds(470, 90, 67, 23);

        jButton5.setText("Get data");
        getContentPane().add(jButton5);
        jButton5.setBounds(590, 90, 75, 20);

        jLabel2.setFont(new java.awt.Font("TeXGyreAdventor", 0, 12)); // NOI18N
        jLabel2.setText("Nama lengkap");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 140, 110, 30);

        jLabel3.setText("Tempat / Tanggal lahir");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 180, 120, 20);

        jLabel4.setText("Pendidikan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 220, 130, 20);

        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 260, 33, 14);

        jLabel6.setText("Nomor HP");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 290, 70, 10);

        jLabel7.setText("Status");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 320, 31, 14);

        jLabel8.setText("Lampiran");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 350, 80, 20);

        jCheckBox1.setText("Daftar riwayat hidup");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(260, 480, 130, 23);

        jCheckBox2.setText("Fotokopi ijazah");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(460, 480, 120, 23);

        jCheckBox3.setText("Fotokopi transkip nilai");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(610, 480, 150, 30);

        jCheckBox4.setText("Fotokopi sertifikat / kursus");
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(660, 420, 170, 20);

        jButton6.setText("Daftar riwayat hidup");
        getContentPane().add(jButton6);
        jButton6.setBounds(170, 380, 140, 30);

        jButton7.setText("Fotokopi ijazah");
        getContentPane().add(jButton7);
        jButton7.setBounds(20, 380, 140, 30);

        jButton8.setText("Fotokopi sertifikiat / kursus");
        getContentPane().add(jButton8);
        jButton8.setBounds(480, 380, 170, 30);

        jButton9.setText("Fotokopi transkrip nilai");
        getContentPane().add(jButton9);
        jButton9.setBounds(320, 380, 150, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
