/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HAI;

import java.awt.HeadlessException;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ivan Rezki
 */
public class Psikotest_Edit extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String sql;

    String stridPsikotest, stridPelamar, stridPsikolog, strhasil, strfile;
    FileInputStream fispsiko;
    int jlhbaris = 0;

    public Psikotest_Edit() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        con = Connect.ConnectDB();
        Get_Data();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        tfidPsikotest = new java.awt.TextField();
        tfidPelamar = new java.awt.TextField();
        tfidPsikolog = new java.awt.TextField();
        tfhasil = new java.awt.TextField();
        label5 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        btnUpdate = new java.awt.Button();
        button2 = new java.awt.Button();
        lbfilename = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableview = new javax.swing.JTable();
        tfsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jFormattedTextField1.setText("PHOTO");
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(110, 200, 113, 98);

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 300, 113, 28);

        jButton3.setText("ADD");
        getContentPane().add(jButton3);
        jButton3.setBounds(100, 340, 154, 23);

        label1.setText("ID Psikotest");

        label2.setText("ID Pelamar");

        label3.setText("ID Psikolog");

        label4.setText("Hasil");

        tfidPsikotest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfidPsikotestKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfidPsikotestKeyTyped(evt);
            }
        });

        tfidPelamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidPelamarActionPerformed(evt);
            }
        });

        tfidPsikolog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidPsikologActionPerformed(evt);
            }
        });

        tfhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhasilActionPerformed(evt);
            }
        });

        label5.setText("File");

        jButton1.setText("Browse...");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnUpdate.setLabel("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        button2.setLabel("Cancel");

        lbfilename.setText("File Name");

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(37, 37, 37)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbfilename, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfidPsikotest, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfhasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfidPelamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfidPsikolog, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfidPsikotest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfidPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfidPsikolog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfhasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(lbfilename)))
                .addGap(30, 30, 30)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(panel1);
        panel1.setBounds(260, 200, 490, 260);

        jButton4.setText("EDIT");
        getContentPane().add(jButton4);
        jButton4.setBounds(100, 370, 154, 23);

        jButton5.setText("VIEW");
        getContentPane().add(jButton5);
        jButton5.setBounds(100, 400, 154, 23);

        tableview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableviewMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableview);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(0, 0, 1030, 150);

        tfsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfsearchKeyReleased(evt);
            }
        });
        getContentPane().add(tfsearch);
        tfsearch.setBounds(400, 160, 150, 30);

        jLabel2.setText("Search ID Psikotest");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 160, 110, 30);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void Get_Data() {
        sql = "select * from tbpsikotest";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            tableview.setModel(DbUtils.resultSetToTableModel(rs));
            tableview.setDefaultEditor(Object.class, null);
            tableview.setAutoCreateRowSorter(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }
    
    private void reset(){
        tfidPsikolog.setText("");
        tfhasil.setText("");
        tfidPelamar.setText("");
        tfidPsikotest.setText("");
        tfsearch.setText("");
        lbfilename.setText("abc");
        
        
    }
    
    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void tfidPelamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidPelamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidPelamarActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        stridPsikotest = tfidPsikotest.getText();
        stridPelamar = tfidPelamar.getText();
        stridPsikolog = tfidPsikolog.getText();
        strhasil = tfhasil.getText();
        strfile = lbfilename.getText();

        try {
            con = Connect.ConnectDB();
            if (stridPsikotest.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter idpsikotest", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (stridPelamar.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter idpelamar", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (stridPsikolog.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter idpsikolog", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (strhasil.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter hasil", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (strfile.equals("")) {
                JOptionPane.showMessageDialog(this, "Please select file", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            jlhbaris = 0;
            Statement stmt;
            stmt = con.createStatement();
            sql = "Select * from tbpsikotest where idPsikotest= '" + stridPsikotest + "'";
            rs = stmt.executeQuery(sql);
            if (rs.next()) {
                
                jlhbaris++;
                return;
            }

            if (jlhbaris == 1) {
                sql = "update tbdatapelamar set idPelamar='" + stridPelamar + "', idPsikolog='" + stridPsikolog + "', hasil='" + strhasil + "', '"
                        + lbfilename + "' where idPsikotest='" + stridPsikotest + "'";

                pst = con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Successfully update data", "Psikotest", JOptionPane.INFORMATION_MESSAGE);
                reset();
            }

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tfidPsikologActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidPsikologActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidPsikologActionPerformed

    private void tfhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhasilActionPerformed

    private void tableviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableviewMouseClicked
        try {
            con = Connect.ConnectDB();
            int row = tableview.getSelectedRow();
            String table_click = tableview.getModel().getValueAt(row, 0).toString();
            sql = "select * from tbpsikotest where idPsikotest = '" + table_click + "'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {

                String colidPsikotest = rs.getString("idPsikotest");
                tfidPsikotest.setText(colidPsikotest);
                String colidPelamar = rs.getString("idPelamar");
                tfidPelamar.setText(colidPelamar);
                String colidPsikolog = rs.getString("idPsikolog");
                tfidPsikolog.setText(colidPsikolog);
                String colhasil = rs.getString("hasil");
                tfhasil.setText(colhasil);
                String coldok = rs.getString("dokPsikotest");
                lbfilename.setText(coldok);
                
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_tableviewMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        stridPsikotest = tfidPsikotest.getText();
       

        try {
            con = Connect.ConnectDB();
            if (stridPsikotest.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter id psikotest to delete", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            

            jlhbaris = 0;
            Statement stmt;
            stmt = con.createStatement();
            sql = "Select * from tbpsikotest where idPsikotest= '" + stridPsikotest + "'";
            rs = stmt.executeQuery(sql);
            if (rs.next()) {
                jlhbaris++;
            }

            if (jlhbaris == 1) {
                sql = "delete from tbpsikotest where idPsikotest='" + stridPsikotest + "'";

                pst = con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Successfully delete data", "Psikotest", JOptionPane.INFORMATION_MESSAGE);
                reset();
                Get_Data();
            }

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
           
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void tfidPsikotestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfidPsikotestKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfidPsikotestKeyTyped

    private void tfidPsikotestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfidPsikotestKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tfidPsikotestKeyReleased

    private void tfsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfsearchKeyReleased
        // TODO add your handling code here:
        String strsearch=tfsearch.getText();
        sql = "select * from tbpsikotest where idPsikotest like '%" + strsearch + "%'";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            tableview.setModel(DbUtils.resultSetToTableModel(rs));
            tableview.setDefaultEditor(Object.class, null);
            tableview.setAutoCreateRowSorter(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_tfsearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser OpenFile = new JFileChooser();
        OpenFile.setMultiSelectionEnabled(false);
        OpenFile.showOpenDialog(null);
        File x_file = OpenFile.getSelectedFile();
        String NamaFile = x_file.getAbsolutePath();
        lbfilename.setText(NamaFile);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Psikotest_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Psikotest_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Psikotest_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Psikotest_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Psikotest_Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private java.awt.Button btnUpdate;
    private java.awt.Button button2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JLabel lbfilename;
    private java.awt.Panel panel1;
    private javax.swing.JTable tableview;
    private java.awt.TextField tfhasil;
    private java.awt.TextField tfidPelamar;
    private java.awt.TextField tfidPsikolog;
    private java.awt.TextField tfidPsikotest;
    private javax.swing.JTextField tfsearch;
    // End of variables declaration//GEN-END:variables
}
